# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    container_name: do_an_2_app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: '<YourRailwayPassword>'

  mysql:
    image: mysql:8.0
    container_name: do_an_2_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: '<YourRailwayPassword>'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
