services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan key:generate --force || true
      php artisan config:cache
      php artisan route:cache || true

    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT

